version: '3'
services:
  postgres:
    image: postgres:17
    container_name: river_postgres
    environment:
      POSTGRES_DB: river_test
      POSTGRES_USER: river_user
      POSTGRES_PASSWORD: river_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U river_user -d river_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:9
    container_name: river_mysql
    environment:
      MYSQL_DATABASE: river_test
      MYSQL_USER: river_user
      MYSQL_PASSWORD: river_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u river_user --password=river_pass"]
      interval: 5s
      timeout: 5s
      retries: 5
