name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.13

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: river_test
          POSTGRES_USER: river_user
          POSTGRES_PASSWORD: river_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U river_user -d river_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: river_test
          MYSQL_USER: river_user
          MYSQL_PASSWORD: river_pass
          MYSQL_ROOT_PASSWORD: root_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -u river_user --password=river_pass"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      POSTGRES_DSN: postgresql://river_user:river_pass@localhost:5432/river_test
      MYSQL_DSN: mysql://river_user:river_pass@localhost:3306/river_test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run pytest
        run: uv run pytest -v
